language: python

services:
  - docker

python: 
  - 3.9
  
script:
  - cd testing/
  - DOCKER_RUN_FLAGS=--detach make run
  - python -m pip install --upgrade pip
  - python -m pip install --requirement requirements.txt

  - docker ps
  - /sbin/ifconfig

  # ... but also wait for logstash to get started. It's slow.
  - docker logs -f $(docker ps -q)
  - until nc -w 5 localhost 7011; do echo "Port not yet open"; sleep 1; done
  - echo "caPutLog port open; logstash appears ready."; sleep 2
  - timeout 100 make test

after_failure:
  - tail -n 100 logs/*.log
