language: python

services:
  - docker

python: 
  - 3.6
  
before_install:
  - make -C testing run
  - python -m pip install --upgrade pip
  - python -m pip install --requirement testing/requirements.txt
  - sleep 30

script:
  - make -C testing test
