language: python

services:
  - docker

python: 
  - 3.9
  
script:
  - cd testing/
  - DOCKER_RUN_FLAGS=--detach make run
  - python -m pip install --upgrade pip
  - python -m pip install --requirement requirements.txt

  - docker ps
  - /sbin/ifconfig

  # ... but also wait for logstash to get started. It's slow.
  - until docker logs $(docker ps -q) |grep "Starting tcp input"; do sleep 1; done
  - echo "logstash appears ready."; sleep 15

  - timeout 100 make test

after_failure:
  - tail -n 100 testing/logs/*.log
  - docker logs $(docker ps -q)
