language: python

services:
  - docker

python: 
  - 3.6
  
before_install:
  - cd testing/
  - DOCKER_RUN_FLAGS=--detach make run
  - python -m pip install --upgrade pip
  - python -m pip install --requirement testing/requirements.txt
  - sleep 30

script: 
  - cd testing/
  - make test
