{
 "title": "EPICS IOCs",
 "description": "caPutLog and Error Log",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "caPutLog Count",
   "type": "graph",
   "description": "Number of reports from IOCs regarding `caput` attempts to PVs.",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:226",
       "field": "log.timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:224", "field": "select field", "id": "1", "type": "count" }
     ],
     "timeField": "log.timestamp"
    }
   ]
  },
  {
   "title": "EPICS errlogs",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:21",
       "field": "log.timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:19", "field": "select field", "id": "1", "type": "count" }
     ],
     "timeField": "log.timestamp"
    }
   ]
  },
  {
   "title": "caPutLog popularity contest (PV)",
   "type": "table",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 11 },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:300",
       "field": "log.pvname.keyword",
       "id": "2",
       "settings": { "min_doc_count": 0, "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:38",
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "timeField": "log.timestamp"
    }
   ]
  },
  {
   "title": "caPutLog popularity contest (user)",
   "type": "table",
   "gridPos": { "h": 6, "w": 7, "x": 10, "y": 11 },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:300",
       "field": "log.client_username.keyword",
       "id": "2",
       "settings": { "min_doc_count": 0, "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:38",
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "timeField": "log.timestamp"
    }
   ]
  },
  {
   "title": "caPutLog popularity contest (host)",
   "type": "table",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 11 },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:300",
       "field": "log.client_hostname.keyword",
       "id": "2",
       "settings": { "min_doc_count": 0, "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:38",
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "timeField": "log.timestamp"
    }
   ]
  }
 ]
}