{
 "title": "Python Overview",
 "description": "Overview of log messages + exceptions from pcdsutils / Python",
 "time": { "from": "2020-06-15T16:48:12.730Z", "to": "2020-06-15T16:57:03.257Z" },
 "panels": [
  {
   "title": "Total Python log messages (pcdsutils)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:90",
       "field": "log.timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:88", "field": "select field", "id": "1", "type": "count" }
     ],
     "timeField": "log.timestamp"
    }
   ]
  },
  {
   "title": "Total Python exceptions",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:90",
       "field": "log.timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:88", "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "log.exc_text:*",
     "timeField": "log.timestamp"
    }
   ]
  },
  {
   "title": "Exceptions by source",
   "type": "table",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 10 },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:257",
       "field": "log.source.keyword",
       "id": "2",
       "settings": { "min_doc_count": 0, "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:255", "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "log.exc_text:*",
     "timeField": "log.timestamp"
    }
   ]
  },
  {
   "title": "Messages by filename",
   "type": "table",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 10 },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:257",
       "field": "log.filename.keyword",
       "id": "2",
       "settings": { "min_doc_count": 0, "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:255", "field": "select field", "id": "1", "type": "count" }
     ],
     "timeField": "log.timestamp"
    }
   ]
  },
  {
   "title": "Messages by filename",
   "type": "table",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 10 },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:257",
       "field": "log.filename.keyword",
       "id": "2",
       "settings": { "min_doc_count": 0, "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:255", "field": "select field", "id": "1", "type": "count" }
     ],
     "timeField": "log.timestamp"
    }
   ]
  }
 ]
}